10/items open new link
graasp/graasp-explore pull request #13
Opened 2021-01-17 15:43 UTC by hasanagh

- wasn't sure about the "activity" demo mode so maybe we can fix in this MR 
- branched from 11

2021-01-19 10:12 UTC, pyphilia approved these changes
For me everything is okay, maybe I'll let @juancarlosfarah give more insights for this PR. I'll merge my own PR so that you can rebase, thank you @hasanagh !

2021-01-22 07:00 UTC, juancarlosfarah commented
@hasanagh, I still see @pyphilia's commit mixed into this PR. Can you rebase?

2021-01-24 12:56 UTC, juancarlosfarah commented
Any update on this @hasanagh ?

2021-01-24 13:45 UTC, hasanagh commented
> Any update on this @hasanagh ?

Hey JC, sorry I just pushed now.

2021-01-25 09:03 UTC, pyphilia commented
I'll rebase it on my changes, and tweak it a bit to use the api as well.

2021-01-25 12:35 UTC, juancarlosfarah requested changes
Thanks @hasanagh for cleaning this up. Just some quick comments and questions here.

2021-01-25 12:35 UTC, juancarlosfarah commented on src/client/config/helpers.js
> +  if (newWindow) newWindow.opener = null;
Brackets around `if` statements, please. Can we force it with `eslint` / `prettier`?

2021-01-25 12:35 UTC, juancarlosfarah commented on src/client/config/helpers.js
> +  console.log('url: ', url);
Remove console log here.

2021-01-25 12:35 UTC, juancarlosfarah commented on src/client/config/routes.js
> +export const HOME_ROUTE = '/*';
Does HOME need an `*`?

2021-01-25 12:35 UTC, juancarlosfarah commented on src/server.js
> +  const id = req.path.split('/')[2];
Comment or helper function to see what this is actually doing. Maybe `id` can be passed in a cleaner way.

2021-01-25 12:49 UTC, merged