feat: add langauge category
graasp/graasp-explore pull request #155
Opened 2022-05-30 15:37 UTC by louisewang1

close #154

2022-05-31 07:53 UTC, pyphilia requested changes
Looks nice! I've added some comments. Do you think it would be possible to create a component for displaying the categories? I think it's three times the same code currently.

2022-05-31 07:53 UTC, pyphilia commented on src/components/home/AllCollections.js
> +                selected={selectedLanguage.indexOf(entry.id) !== -1}
I think you can use `.find` instead 
```
selectedLanguage.find(l => l.id === entry.id)
```

2022-05-31 07:53 UTC, pyphilia commented on src/components/home/AllCollections.js
> +  const [selectedLanguage, setSelectedLangauge] = useState([]);
We can use plurals for these arrays since we can choose multiple choices, right?

2022-05-31 07:53 UTC, pyphilia commented on src/components/home/AllCollections.js
> +              selectedLanguage={selectedLanguage}
Use plural?

2022-06-02 13:37 UTC, louisewang1 commented
![image](https://user-images.githubusercontent.com/25419619/171641718-8be83a2a-a2f9-4c4a-99f6-e5b71a2fbceb.png)

Split the language out of other categories, and use different color outline different category types. The secondary color is a bit to red, use other colors? @pyphilia

2022-06-06 10:31 UTC, pyphilia requested changes
Looks good to me! There's a minor typo. Also, would it be possible to write some tests? (layout tests depending on if the item has a language or not).
The categories are nicely divided. But maybe let's not use red, let's use everything in blue and we'll see later 🎈

2022-06-06 10:31 UTC, pyphilia commented on src/components/home/AllCollections.js
> +    setSelectedLangauges,
Typo `setSelectedLanguages` (a-u misplaced)

2022-06-06 14:22 UTC, merged